# Generated by Django 3.2.8 on 2021-11-29 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerName',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Customer Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.BigIntegerField(verbose_name='Customer Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer_on_ticket',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_On_Ticket', to='ticketing_system.customer', verbose_name='Customer Ticket Belongs To'),
        ),
        migrations.AlterField(
            model_name='staff_on_ticket',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff_On_Ticket', to='ticketing_system.staff', verbose_name='Staff Member Servicing Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completedStatus',
            field=models.BooleanField(default=False, verbose_name='Order Completed'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='orderDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='specialRequests',
            field=models.CharField(max_length=500, verbose_name='Special Requests'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timeToFulfill',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Time To Fulfill (Minutes)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tip (Percentage)'),
        ),
        migrations.AlterField(
            model_name='ticket_item',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='ticket_item',
            name='itemID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item_Ticket', to='ticketing_system.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='ticket_item',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='Quantity'),
        ),
    ]
